version: '3.7'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  flow-collector:
    image: elastiflow/flow-collector:5.2.0
    container_name: flow-collector
    restart: 'unless-stopped'
    network_mode: 'host'
    volumes:
      - /etc/elastiflow:/etc/elastiflow
    environment:
      EF_FLOW_SERVER_UDP_IP: '0.0.0.0'
      EF_FLOW_SERVER_UDP_PORT: 9995
      EF_FLOW_DECODER_ENRICH_IPADDR_METADATA_ENABLE: 'false'
      EF_FLOW_DECODER_ENRICH_DNS_ENABLE: 'false'
      EF_FLOW_DECODER_ENRICH_DNS_NAMESERVER_IP: ''
      EF_FLOW_DECODER_ENRICH_DNS_NAMESERVER_TIMEOUT: 3000
      EF_FLOW_DECODER_ENRICH_MAXMIND_ASN_ENABLE: 'false'
      EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_ENABLE: 'false'
      EF_FLOW_DECODER_ENRICH_RISKIQ_ASN_ENABLE: 'false'
      EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_ENABLE: 'false'
      EF_FLOW_OUTPUT_ELASTICSEARCH_ENABLE: 'true'
      EF_FLOW_OUTPUT_ELASTICSEARCH_ECS_ENABLE: 'false'
      EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_SHARDS: 1
      EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_REPLICAS: 0
      EF_FLOW_OUTPUT_ELASTICSEARCH_ADDRESSES: '127.0.0.1:9200'
      EF_FLOW_OUTPUT_ELASTICSEARCH_USERNAME: 'elastic'
      EF_FLOW_OUTPUT_ELASTICSEARCH_PASSWORD: 'changeme'
      EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_ENABLE: 'false'
      EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_SKIP_VERIFICATION: 'false'
      EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_CA_CERT_FILEPATH: ''
      EF_FLOW_OUTPUT_SPLUNK_HEC_ENABLE: 'false'
      EF_FLOW_OUTPUT_SPLUNK_HEC_HOST: ''
      EF_FLOW_OUTPUT_SPLUNK_HEC_TOKEN: ''
      EF_FLOW_OUTPUT_LOGZIO_ENABLE: 'false'
      EF_FLOW_OUTPUT_LOGZIO_TOKEN: ''
      EF_FLOW_OUTPUT_KAFKA_ENABLE: 'false'
      EF_FLOW_OUTPUT_KAFKA_BROKERS: ''
      EF_FLOW_OUTPUT_KAFKA_SASL_ENABLE: 'false'
      EF_FLOW_OUTPUT_RISKIQ_ENABLE: 'false'

  sflow:
    image: sflow/sflow-rt
    container_name: sflow
    ports:
      - 6343:6343/udp
      - 8008:8008/udp
    environment:
      RTMEM: '2G'
      
volumes:
  elasticsearch-data:
    driver: local
